import { spawnSync } from 'node:child_process';
import { resolve, join } from 'node:path';
import { cpSync, mkdirSync, rmSync } from 'node:fs';
const root = resolve('..');
const python = process.env.AIRCARD_PYTHON || join(root, '.tmp/windows-prototype-py312', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python');
const destination = resolve('src-tauri/binaries');
const args = ['-m', 'PyInstaller', '--noconfirm', '--clean', '--name', 'aircard-backend', '--onedir', '--distpath', join(root, 'build/desktop-backend'), '--workpath', join(root, 'build/pyinstaller'), '--specpath', join(root, 'build'), '--hidden-import', 'pymobiledevice3.services.afc', '--hidden-import', 'pymobiledevice3.lockdown', '--hidden-import', 'pymobiledevice3.usbmux', '--hidden-import', 'pefile'];
if (process.platform === 'darwin') args.push('--add-binary', join(root, 'build/airtraffic_host') + ':bin');
args.push(join(root, 'desktop_backend.py'));
const result = spawnSync(python, args, { cwd: root, stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status || 1);
mkdirSync(destination, { recursive: true });
const target = resolve(destination, 'backend');
if (target !== join(root, 'desktop', 'src-tauri', 'binaries', 'backend')) throw new Error('Invalid packaging destination');
rmSync(target, { recursive: true, force: true });
cpSync(join(root, 'build/desktop-backend/aircard-backend'), target, { recursive: true, force: true });
